version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: weatherDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5455:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2021-01-05T05-22-38Z
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc config host add myminio http://minio:9000 access_key secret_key;
        /usr/bin/mc mb --ignore-existing myminio/anadea-hakaton;
        exit 0;
      "

volumes:
  postgres_data:
  minio_data:
